name: Update ROBLOX 2016 Userstyle

on:
  push:
    paths:
      - stylustheme.css
  schedule:
    - cron: "*/5 * * * *"

env:
  CUR_DATE: "$(date +'%m-%d')"

jobs:
  update_roblox_2016:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set user identity
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Create file
      run: |
        echo "/* ==UserStyle==
    @name           ROBLOX 2016 dev$CUR_DATE
    @namespace      Userstyle
    @author         anthony1x6000
    @description    `Userstyle that changes the look of ROBLOX to be more faithful to what it would look like in 2016.`
    @version        p$CUR_DATE
    @license        MIT License
==/UserStyle== */" > roblox2016-pre$CUR_DATE.user.css
        echo >> roblox2016-pre$CUR_DATE.user.css
        cat stylustheme.css >> roblox2016-pre$CUR_DATE.user.css

    - name: Checkout dev branch
      run: |
        git checkout -b dev

    - name: Add changes
      run: |
        git add stylustheme.css
        git add roblox2016-pre$CUR_DATE.user.css

    - name: Commit changes
      run: |
        git commit -m "Add roblox2016-pre$CUR_DATE.user.css"

    - name: Push changes
      run: |
        git push -u origin dev
