name: ROBLOX 2016 Dev Release

on:
  push:
    branches:
      - main

env:
  CUR_DATE: $(date +%m-%d)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Modify stylustheme.css
      run: |
        echo "/* ==UserStyle==
            @name           ROBLOX 2016 dev${CUR_DATE}
            @namespace      Userstyle
            @author         anthony1x6000
            @description    `Userstyle that changes the look of ROBLOX to be more faithful to what it would look like in 2016.`
            @version        p${CUR_DATE}
            @license        MIT License
        ==/UserStyle== */" > roblox2016-pre${CUR_DATE}.user.css
        cat stylustheme.css >> roblox2016-pre${CUR_DATE}.user.css

    - name: Checkout dev branch
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Set user identity
      run: |
        git config --global user.email "contact.b7hkd@simplelogin.fr"
        git config --global user.name "anthony1x6000"

    - name: Commit changes
      run: |
        git add roblox2016-pre${CUR_DATE}.user.css
        git commit -m "Add roblox2016-pre${CUR_DATE}.user.css"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
