name: Stylus Theme Workflow

on:
  push:
    branches:
      - main
    paths:
      - stylustheme.css

env:
  CURDASH_DATE: ${{ format('MM-DD-YY', 'yyyy-MM-dd') }}
  CURDOT_DATE: ${{ format('MM.DD.YY', 'yyyy-MM-dd') }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set user identity
      run: |
        git config --global user.email "contact.b7hkd@simplelogin.fr"
        git config --global user.name "anthony1x6000"

    - name: Add header to stylustheme.css
      run: |
        cat stylustheme.css >> roblox2016Dev${CURDASH_DATE}.user.css

    - name: Create dev branch
      run: |
        git branch dev
        git checkout dev

    - name: Commit modified file
      run: |
        git add roblox2016Dev${CURDASH_DATE}.user.css
        git commit -m "Add roblox2016Dev${CURDASH_DATE}.user.css"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev