name: Stylus Theme Commit Workflow

on:
  push:
    branches:
      - main
    paths:
      - stylustheme.css

env:
  CURDASH_DATE: "$(date +'%m-%d')"
  CURDOT_DATE: "$(date +'%m.%d')"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set User Identity
      run: |
        git config --global user.email "contact.b7hkd@simplelogin.fr"
        git config --global user.name "anthony1x6000"

    - name: Modify Stylus Theme File
      run: |
        echo "/* ==UserStyle==" >> roblox2016Dev$CURDASH_DATE.user.css
        echo "    @name           ROBLOX 2016 dev$CURDASH_DATE" >> roblox2016Dev$CURDASH_DATE.user.css
        echo "    @namespace      Userstyle" >> roblox2016Dev$CURDASH_DATE.user.css
        echo "    @author         anthony1x6000" >> roblox2016Dev$CURDASH_DATE.user.css
        echo "    @description    `Userstyle that changes the look of ROBLOX to be more faithful to what it would look like in 2016.`" >> roblox2016Dev$CURDASH_DATE.user.css
        echo "    @version        $CURDOT_DATE" >> roblox2016Dev$CURDASH_DATE.user.css
        echo "    @license        MIT License" >> roblox2016Dev$CURDASH_DATE.user.css
        echo "==/UserStyle== */" >> roblox2016Dev$CURDASH_DATE.user.css
      
    - name: Create Dev Branch
      run: |
        git branch dev
        git checkout dev

    - name: Commit File to Dev Branch
      run: |
        git add roblox2016Dev$CURDASH_DATE.user.css
        git commit -m "Adding roblox2016Dev$CURDASH_DATE.user.css file"

    - name: Push Changes to Dev Branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
        force: true
