name: ROBLOX 2016 dev Workflow

on:
  push:
    branches:
      - main
    paths:
      - stylustheme.css

env:
  CURDASH_DATE: "$(date +'%m-%d')"
  CURDOT_DATE: "$(date +'%m.%d')"

jobs:
  roblox2016Dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set user identity
      run: |
        git config --global user.email "contact.b7hkd@simplelogin.fr"
        git config --global user.name "anthony1x6000"

    - name: Add header to stylustheme.css
      run: |
        echo "/* ==UserStyle==
        @name           ROBLOX 2016 dev$CURDASH_DATE
        @namespace      Userstyle
        @author         anthony1x6000
        @description    `Userstyle that changes the look of ROBLOX to be more faithful to what it would look like in 2016.`
        @version        $CURDOT_DATE
        @license        MIT License
        ==/UserStyle== */" >> stylustheme.css

    - name: Rename stylustheme.css to roblox2016Dev$CURDASH_DATE.user.css
      run: |
        mv stylustheme.css roblox2016Dev$CURDASH_DATE.user.css

    - name: Create dev branch
      run: |
        git checkout --orphan dev

    - name: Commit roblox2016Dev$CURDASH_DATE.user.css to dev branch
      run: |
        git add roblox2016Dev$CURDASH_DATE.user.css
        git commit -m "Adding roblox2016Dev$CURDASH_DATE.user.css to dev branch"

    - name: Push to dev branch
      uses: ad-m/github-push-action@master
      with:
        branch: dev
        force_with_lease: true
