name: ROBLOX 2016 dev

on:
  push:
    branches:
      - main
    paths:
      - stylustheme.css

env:
  CURDASH_DATE: ${{ format('MM-DD', 'now') }}
  CURDOT_DATE: ${{ format('MM.DD', 'now') }}

jobs:
  create_roblox_css:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set user identity
      run: |
        git config --global user.email "contact.b7hkd@simplelogin.fr"
        git config --global user.name "anthony1x6000"

    - name: Add header to stylustheme.css
      run: |
        echo "/* ==UserStyle==
    @name           ROBLOX 2016 dev$CURDASH_DATE
    @namespace      Userstyle
    @author         anthony1x6000
    @description    `Userstyle that changes the look of ROBLOX to be more faithful to what it would look like in 2016.`
    @version        $CURDOT_DATE
    @license        MIT License
==/UserStyle== */" | cat - stylustheme.css > temp && mv temp stylustheme.css

    - name: Create dev branch
      run: |
        git checkout --orphan dev
        git rm -rf .

    - name: Commit roblox2016Dev file
      run: |
        mv stylustheme.css roblox2016Dev$CURDASH_DATE.user.css
        git add roblox2016Dev$CURDASH_DATE.user.css
        git commit -m "Commit roblox2016Dev$CURDASH_DATE.user.css file"
        git push -u origin dev
